Repository framgia/sph-ojt-blog, pull requests merged in 2022-08, with the labels that each got.

#2 Blog Detail Backend Development
  .gitignore
  backend/blog_backend/__pycache__/__init__.cpython-310.pyc
  backend/blog_backend/__pycache__/settings.cpython-310.pyc
  backend/blog_backend/__pycache__/urls.cpython-310.pyc
  backend/blog_backend/__pycache__/wsgi.cpython-310.pyc
  backend/post/__pycache__/__init__.cpython-310.pyc
  backend/post/__pycache__/admin.cpython-310.pyc
  backend/post/__pycache__/apps.cpython-310.pyc
  backend/post/__pycache__/models.cpython-310.pyc
  backend/post/__pycache__/serializers.cpython-310.pyc
  backend/post/__pycache__/urls.cpython-310.pyc
  backend/post/__pycache__/views.cpython-310.pyc
  backend/post/migrations/__pycache__/0001_initial.cpython-310.pyc
  backend/post/migrations/__pycache__/0002_post_published_at_post_total_votes.cpython-310.pyc
  backend/post/migrations/__pycache__/0003_alter_post_published_at_alter_post_total_votes.cpython-310.pyc
  backend/post/migrations/__pycache__/0004_post_author.cpython-310.pyc
  backend/post/migrations/__pycache__/0005_post_excerpt.cpython-310.pyc
  backend/post/migrations/__pycache__/0006_post_slug.cpython-310.pyc
  backend/post/migrations/__pycache__/__init__.cpython-310.pyc
  backend/post/models.py
  backend/post/urls.py
  backend/post/views.py
Labels: Approved By Kent

#4 Migrate Comments, Dummy users, and Votes, to database
  backend/db.sqlite3
  backend/post/admin.py
  backend/post/migrations/0007_dummyuser_remove_post_total_votes_vote_comment_and_more.py
  backend/post/models.py
Labels: Approved by Kent

#8 Blog List Page Frontend Development
  frontend/src/App.js
  frontend/src/BlogList/BlogContainer.js
  frontend/src/BlogList/BlogList.css
  frontend/src/BlogList/BlogList.js
  frontend/src/BlogList/PaginationList.js
  frontend/src/Navbar/NavBar.js
Labels: Approved by Kent

#9 Backend Registration
  backend/blog_backend/settings.py
  backend/blog_backend/urls.py
  backend/db.sqlite3
  backend/registration/__init__.py
  backend/registration/admin.py
  backend/registration/apps.py
  backend/registration/migrations/__init__.py
  backend/registration/models.py
  backend/registration/serializers.py
  backend/registration/tests.py
  backend/registration/urls.py
  backend/registration/views.py
  backend/requirements.txt
Labels: Approved by Kent

#10 Registration Page FE
  frontend/public/Images/Check.png
  frontend/public/Images/RegIm.jpg
  frontend/public/Images/RegIm2.jpg
  frontend/public/index.html
  frontend/src/Navbar/NavBar.css
  frontend/src/Navbar/NavBar.js
  frontend/src/RegistrationPage/Form.css
  frontend/src/RegistrationPage/Form.js
  frontend/src/RegistrationPage/FormSignup.js
  frontend/src/RegistrationPage/FormSuccess.js
  frontend/src/RegistrationPage/useForm.js
  frontend/src/RegistrationPage/validateInfo.js
Labels: Chevy is Reviewing

#5 Blog Detail and API Integration
  backend/db.sqlite3
  backend/post/serializers.py
  frontend/src/App.js
  frontend/src/BlogDetail/BlogDetail.js
  frontend/src/BlogList/BlogList.js
  frontend/src/HomePage/HomePage.js
  frontend/src/Navbar/NavBar.css
  frontend/src/RegistrationPage/FormSignup.js
  frontend/src/components/ListItem/ListItem.js
  frontend/src/components/Template/Footer.css
  frontend/src/components/Template/Footer.js
  frontend/src/components/Template/NavBar.css
  frontend/src/components/Template/NavBar.js
  frontend/src/components/Template/Template.js
  frontend/src/helpers/getContent.js
  frontend/src/helpers/getDate.js
  frontend/src/helpers/getTitle.js
  frontend/src/helpers/useFetch.js
  frontend/src/pages/404 Page/PageNotFound.js
  frontend/src/pages/404 Page/PageNotFound.module.css
  frontend/src/pages/BlogDetail/BlogDetail.js
  frontend/src/pages/BlogDetail/Comments.js
  frontend/src/pages/BlogList/BlogContainer.js
  frontend/src/pages/BlogList/BlogList.css
  frontend/src/pages/BlogList/BlogList.js
  frontend/src/pages/BlogList/PaginationList.js
  frontend/src/pages/HomePage/HomePage.js
  frontend/src/pages/RegistrationPage/Form.css
  frontend/src/pages/RegistrationPage/Form.js
  frontend/src/pages/RegistrationPage/FormSignup.js
  frontend/src/pages/RegistrationPage/FormSuccess.js
  frontend/src/pages/RegistrationPage/useForm.js
  frontend/src/pages/RegistrationPage/validateInfo.js
Labels: Chevy is Reviewing, conflict

#14 Blog List Page and API Integration
  backend/db.sqlite3
  backend/post/pagination.py
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/ListItem/ListItem.js
  frontend/src/components/ListItem/styles.module.css
  frontend/src/components/Loader/Loader.js
  frontend/src/components/Template/Footer.css
  frontend/src/components/Template/Footer.js
  frontend/src/components/Template/NavBar.js
  frontend/src/helpers/getContent.js
  frontend/src/helpers/useFetch.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/pages/BlogDetail/BlogDetail.js
  frontend/src/pages/BlogDetail/Comments.js
  frontend/src/pages/BlogList/BlogContainer.js
  frontend/src/pages/BlogList/BlogList.css
  frontend/src/pages/BlogList/BlogList.js
  frontend/src/pages/BlogList/PaginationList.js
  frontend/src/pages/HomePage/HomePage.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: Approved by Chevy

#17 New Fixed "Refactor models.py and fix comment bug"
  backend/blog_backend/urls.py
  backend/db.sqlite3
  backend/post/migrations/0008_alter_comment_options_alter_post_options_and_more.py
  backend/post/models.py
  backend/post/serializers.py
  backend/post/views.py
Labels: Approved by Chevy

#11 Pre frontend of blog Home
  frontend/src/App.js
  frontend/src/pages/HomePage/HomePage.css
  frontend/src/pages/HomePage/HomePage.js
Labels: Approved by Kent

#15 Adding a login api in the registration app
  backend/blog_backend/settings.py
  backend/db.sqlite3
  backend/registration/admin.py
  backend/registration/apps.py
  backend/registration/models.py
  backend/registration/serializers.py
  backend/registration/urls.py
  backend/registration/views.py
  backend/requirements.txt
Labels: Approved by Chevy, Approved by Kent

#19 login page frontend
  frontend/src/components/Template/NavBar.css
  frontend/src/components/Template/NavBar.js
  frontend/src/pages/LogInPage/LogInPage.css
  frontend/src/pages/LogInPage/LogInPage.js
Labels: Approved by Chevy
